name = "layers-push"
main = "src/index.js"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[kv_namespaces]]
binding = "SUBS"
id = "d17afd18e6674a1f9103693a9dd0b2a9"

[triggers]
crons = ["0 * * * *"] # every hour at :00 UTC

# Required secrets:
#   wrangler secret put VAPID_PUBLIC_KEY
#   wrangler secret put VAPID_PRIVATE_KEY
#   wrangler secret put VAPID_SUBJECT     # e.g. mailto:you@example.com
